/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAiSettingsRouteImport } from './routes/_app/ai-settings'
import { Route as AppAlertsRouteImport } from './routes/_app/alerts'
import { Route as AppAnalysisRouteImport } from './routes/_app/analysis'
import { Route as AppAssetIdentityRouteImport } from './routes/_app/asset-identity'
import { Route as AppAuditRouteImport } from './routes/_app/audit'
import { Route as AppBaselineRouteImport } from './routes/_app/baseline'
import { Route as AppDetectionRulesRouteImport } from './routes/_app/detection-rules'
import { Route as AppFieldDictionaryRouteImport } from './routes/_app/field-dictionary'
import { Route as AppKnowledgeBaseRouteImport } from './routes/_app/knowledge-base'
import { Route as AppLicenseRouteImport } from './routes/_app/license'
import { Route as AppNotifyRouteImport } from './routes/_app/notify'
import { Route as AppPlatformRouteImport } from './routes/_app/platform'
import { Route as AppPostureRouteImport } from './routes/_app/posture'
import { Route as AppPreferencesRouteImport } from './routes/_app/preferences'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppReportsRouteImport } from './routes/_app/reports'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppTriageRouteImport } from './routes/_app/triage'
import { Route as AppUsersRouteImport } from './routes/_app/users'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAiSettingsRoute = AppAiSettingsRouteImport.update({
  id: '/ai-settings',
  path: '/ai-settings',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertsRoute = AppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalysisRoute = AppAnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => AppRoute,
} as any)
const AppAssetIdentityRoute = AppAssetIdentityRouteImport.update({
  id: '/asset-identity',
  path: '/asset-identity',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppBaselineRoute = AppBaselineRouteImport.update({
  id: '/baseline',
  path: '/baseline',
  getParentRoute: () => AppRoute,
} as any)
const AppDetectionRulesRoute = AppDetectionRulesRouteImport.update({
  id: '/detection-rules',
  path: '/detection-rules',
  getParentRoute: () => AppRoute,
} as any)
const AppFieldDictionaryRoute = AppFieldDictionaryRouteImport.update({
  id: '/field-dictionary',
  path: '/field-dictionary',
  getParentRoute: () => AppRoute,
} as any)
const AppKnowledgeBaseRoute = AppKnowledgeBaseRouteImport.update({
  id: '/knowledge-base',
  path: '/knowledge-base',
  getParentRoute: () => AppRoute,
} as any)
const AppLicenseRoute = AppLicenseRouteImport.update({
  id: '/license',
  path: '/license',
  getParentRoute: () => AppRoute,
} as any)
const AppNotifyRoute = AppNotifyRouteImport.update({
  id: '/notify',
  path: '/notify',
  getParentRoute: () => AppRoute,
} as any)
const AppPlatformRoute = AppPlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => AppRoute,
} as any)
const AppPostureRoute = AppPostureRouteImport.update({
  id: '/posture',
  path: '/posture',
  getParentRoute: () => AppRoute,
} as any)
const AppPreferencesRoute = AppPreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppTriageRoute = AppTriageRouteImport.update({
  id: '/triage',
  path: '/triage',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/ai-settings': typeof AppAiSettingsRoute
  '/alerts': typeof AppAlertsRoute
  '/analysis': typeof AppAnalysisRoute
  '/asset-identity': typeof AppAssetIdentityRoute
  '/audit': typeof AppAuditRoute
  '/baseline': typeof AppBaselineRoute
  '/detection-rules': typeof AppDetectionRulesRoute
  '/field-dictionary': typeof AppFieldDictionaryRoute
  '/knowledge-base': typeof AppKnowledgeBaseRoute
  '/license': typeof AppLicenseRoute
  '/notify': typeof AppNotifyRoute
  '/platform': typeof AppPlatformRoute
  '/posture': typeof AppPostureRoute
  '/preferences': typeof AppPreferencesRoute
  '/profile': typeof AppProfileRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/triage': typeof AppTriageRoute
  '/users': typeof AppUsersRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/ai-settings': typeof AppAiSettingsRoute
  '/alerts': typeof AppAlertsRoute
  '/analysis': typeof AppAnalysisRoute
  '/asset-identity': typeof AppAssetIdentityRoute
  '/audit': typeof AppAuditRoute
  '/baseline': typeof AppBaselineRoute
  '/detection-rules': typeof AppDetectionRulesRoute
  '/field-dictionary': typeof AppFieldDictionaryRoute
  '/knowledge-base': typeof AppKnowledgeBaseRoute
  '/license': typeof AppLicenseRoute
  '/notify': typeof AppNotifyRoute
  '/platform': typeof AppPlatformRoute
  '/posture': typeof AppPostureRoute
  '/preferences': typeof AppPreferencesRoute
  '/profile': typeof AppProfileRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/triage': typeof AppTriageRoute
  '/users': typeof AppUsersRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/ai-settings': typeof AppAiSettingsRoute
  '/_app/alerts': typeof AppAlertsRoute
  '/_app/analysis': typeof AppAnalysisRoute
  '/_app/asset-identity': typeof AppAssetIdentityRoute
  '/_app/audit': typeof AppAuditRoute
  '/_app/baseline': typeof AppBaselineRoute
  '/_app/detection-rules': typeof AppDetectionRulesRoute
  '/_app/field-dictionary': typeof AppFieldDictionaryRoute
  '/_app/knowledge-base': typeof AppKnowledgeBaseRoute
  '/_app/license': typeof AppLicenseRoute
  '/_app/notify': typeof AppNotifyRoute
  '/_app/platform': typeof AppPlatformRoute
  '/_app/posture': typeof AppPostureRoute
  '/_app/preferences': typeof AppPreferencesRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/triage': typeof AppTriageRoute
  '/_app/users': typeof AppUsersRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/ai-settings'
    | '/alerts'
    | '/analysis'
    | '/asset-identity'
    | '/audit'
    | '/baseline'
    | '/detection-rules'
    | '/field-dictionary'
    | '/knowledge-base'
    | '/license'
    | '/notify'
    | '/platform'
    | '/posture'
    | '/preferences'
    | '/profile'
    | '/reports'
    | '/settings'
    | '/triage'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/ai-settings'
    | '/alerts'
    | '/analysis'
    | '/asset-identity'
    | '/audit'
    | '/baseline'
    | '/detection-rules'
    | '/field-dictionary'
    | '/knowledge-base'
    | '/license'
    | '/notify'
    | '/platform'
    | '/posture'
    | '/preferences'
    | '/profile'
    | '/reports'
    | '/settings'
    | '/triage'
    | '/users'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/ai-settings'
    | '/_app/alerts'
    | '/_app/analysis'
    | '/_app/asset-identity'
    | '/_app/audit'
    | '/_app/baseline'
    | '/_app/detection-rules'
    | '/_app/field-dictionary'
    | '/_app/knowledge-base'
    | '/_app/license'
    | '/_app/notify'
    | '/_app/platform'
    | '/_app/posture'
    | '/_app/preferences'
    | '/_app/profile'
    | '/_app/reports'
    | '/_app/settings'
    | '/_app/triage'
    | '/_app/users'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai-settings': {
      id: '/_app/ai-settings'
      path: '/ai-settings'
      fullPath: '/ai-settings'
      preLoaderRoute: typeof AppAiSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/alerts': {
      id: '/_app/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AppAlertsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analysis': {
      id: '/_app/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AppAnalysisRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/asset-identity': {
      id: '/_app/asset-identity'
      path: '/asset-identity'
      fullPath: '/asset-identity'
      preLoaderRoute: typeof AppAssetIdentityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit': {
      id: '/_app/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/baseline': {
      id: '/_app/baseline'
      path: '/baseline'
      fullPath: '/baseline'
      preLoaderRoute: typeof AppBaselineRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/detection-rules': {
      id: '/_app/detection-rules'
      path: '/detection-rules'
      fullPath: '/detection-rules'
      preLoaderRoute: typeof AppDetectionRulesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/field-dictionary': {
      id: '/_app/field-dictionary'
      path: '/field-dictionary'
      fullPath: '/field-dictionary'
      preLoaderRoute: typeof AppFieldDictionaryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/knowledge-base': {
      id: '/_app/knowledge-base'
      path: '/knowledge-base'
      fullPath: '/knowledge-base'
      preLoaderRoute: typeof AppKnowledgeBaseRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/license': {
      id: '/_app/license'
      path: '/license'
      fullPath: '/license'
      preLoaderRoute: typeof AppLicenseRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notify': {
      id: '/_app/notify'
      path: '/notify'
      fullPath: '/notify'
      preLoaderRoute: typeof AppNotifyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/platform': {
      id: '/_app/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof AppPlatformRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/posture': {
      id: '/_app/posture'
      path: '/posture'
      fullPath: '/posture'
      preLoaderRoute: typeof AppPostureRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/preferences': {
      id: '/_app/preferences'
      path: '/preferences'
      fullPath: '/preferences'
      preLoaderRoute: typeof AppPreferencesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/triage': {
      id: '/_app/triage'
      path: '/triage'
      fullPath: '/triage'
      preLoaderRoute: typeof AppTriageRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAiSettingsRoute: typeof AppAiSettingsRoute
  AppAlertsRoute: typeof AppAlertsRoute
  AppAnalysisRoute: typeof AppAnalysisRoute
  AppAssetIdentityRoute: typeof AppAssetIdentityRoute
  AppAuditRoute: typeof AppAuditRoute
  AppBaselineRoute: typeof AppBaselineRoute
  AppDetectionRulesRoute: typeof AppDetectionRulesRoute
  AppFieldDictionaryRoute: typeof AppFieldDictionaryRoute
  AppKnowledgeBaseRoute: typeof AppKnowledgeBaseRoute
  AppLicenseRoute: typeof AppLicenseRoute
  AppNotifyRoute: typeof AppNotifyRoute
  AppPlatformRoute: typeof AppPlatformRoute
  AppPostureRoute: typeof AppPostureRoute
  AppPreferencesRoute: typeof AppPreferencesRoute
  AppProfileRoute: typeof AppProfileRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTriageRoute: typeof AppTriageRoute
  AppUsersRoute: typeof AppUsersRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAiSettingsRoute: AppAiSettingsRoute,
  AppAlertsRoute: AppAlertsRoute,
  AppAnalysisRoute: AppAnalysisRoute,
  AppAssetIdentityRoute: AppAssetIdentityRoute,
  AppAuditRoute: AppAuditRoute,
  AppBaselineRoute: AppBaselineRoute,
  AppDetectionRulesRoute: AppDetectionRulesRoute,
  AppFieldDictionaryRoute: AppFieldDictionaryRoute,
  AppKnowledgeBaseRoute: AppKnowledgeBaseRoute,
  AppLicenseRoute: AppLicenseRoute,
  AppNotifyRoute: AppNotifyRoute,
  AppPlatformRoute: AppPlatformRoute,
  AppPostureRoute: AppPostureRoute,
  AppPreferencesRoute: AppPreferencesRoute,
  AppProfileRoute: AppProfileRoute,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTriageRoute: AppTriageRoute,
  AppUsersRoute: AppUsersRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
